//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linq_db_ex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public int empno { get; set; }
        public string desig { get; set; }
        public string nam { get; set; }
    }
}
